name: format-lint

on: push

jobs:
  format-lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: exp_action
        python-version: 3.7
        auto-activate-base: false
    - name: Initial setup
      shell: bash -l {0}
      run: make setup
    - name: Format with black, isort
      shell: bash -l {0}
      run: make format
    - name: Lint with pylint, mypy, flake8 using pytest
      shell: bash -l {0}
      run: make lint-all
