name: check pr convention
on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles in the form "ch-1234 Message".
          regex: '^ch-\d+ '
          max_length: 72
