name: unittest

on: push

jobs:
  unittest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: project-chip-placement
        python-version: 3.7
        auto-activate-base: false
    - name: Initial setup
      shell: bash -l {0}
      run: make setup
    - name: Unit test with 'unittest/' codes
      shell: bash -l {0}
      run: make utest
